server:
  port: 8900
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/artisan?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservice-provider-user  #  指定注册到Eureka的应用的名字，建议全部小写
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.artisan: DEBUG
    
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://artisan:artisan123@localhost:8761/eureka
  instance:
    prefer-ip-address: true  # 当鼠标悬浮在服务上，左下角的名称显示IP，或者点击进去之后打开的新页面以ip的形式显示
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}