server:
  port: 7901
user: 
  userServicePath: http://localhost:7900/user/
  
spring:
  application:
    name: micorservice-consumer-movie  
#eureka
eureka: 
  client:
    service-url:
      defaultZone: http://artisan:artisan123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}