server:
  port: 7902

spring:
  application:
    name: micorservice-consumer-movie-ribbon-hystrix
#eureka
eureka: 
  client:
    service-url:
      defaultZone: http://artisan:artisan123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

#actuator  启用所有的监控端点 “*”号代表启用所有的监控端点，可以单独启用，例如，health，info，metrics
management:
  endpoints:
    web:
      exposure:
        include: "*" 