server:
  port: 7902

spring:
  application:
    name: micorservice-consumer-movie-ribbon-customrule-properties
#eureka
eureka: 
  client:
    service-url:
      defaultZone: http://artisan:artisan123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
#使用属性自定义Ribbon配置
microservice-provider-user: 
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule